=== calebhearth/bwapi/trunk/bwapi/starcraft-folder/bwapi-data/build-order.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

 <xs:import namespace="http://www.w3.org/XML/1998/namespace">
   <xs:annotation>
     <xs:documentation>
        The schemaLocation of the relevant file is
        "http://www.w3.org/2001/xml.xsd"; however,
        we don"t want to assume people are always
        connected to the "net when playing with this file.
     </xs:documentation>
   </xs:annotation>
 </xs:import>
   
 <xs:element name="build-orders">
   <xs:complexType>
     <xs:sequence>
       <xs:element ref="build-order"/>
     </xs:sequence>
   </xs:complexType>
 </xs:element> 

 <xs:element name="build-order">
   <xs:complexType>
     <xs:choice minOccurs="0" maxOccurs="unbounded">
       <xs:element name="build">
         <xs:complexType>
            <xs:sequence>
              <xs:element ref="condition" minOccurs="0" maxOccurs="1" />
           </xs:sequence>
           <xs:attribute name="name" type="xs:string" use="required"/>
           <xs:attribute name="place" type="xs:string" use="required"/>
           <xs:attribute name="minimal-population" type="xs:int" use="optional"/>
         </xs:complexType>
       </xs:element>
       <xs:element name="invent">
         <xs:complexType>
            <xs:sequence>
              <xs:element ref="condition" minOccurs="0" maxOccurs="1" />
           </xs:sequence>
           <xs:attribute name="name" type="tech-type" use="required"/>
           <xs:attribute name="minimal-population" type="xs:int" use="optional"/>
         </xs:complexType>
       </xs:element>
       <xs:element name="upgrade">
         <xs:complexType>
            <xs:sequence>
              <xs:element ref="condition" minOccurs="0" maxOccurs="1" />
           </xs:sequence>
           <xs:attribute name="name" type="upgrade-type" use="required"/>
           <xs:attribute name="minimal-population" type="xs:int" use="optional"/>
         </xs:complexType>
       </xs:element>       
       <xs:element name="set-building-rate">
         <xs:complexType>
           <xs:sequence>
             <xs:element ref="condition" minOccurs="0" maxOccurs="1" />
             <xs:element name="build" maxOccurs="unbounded">
               <xs:complexType>
                 <xs:attribute name="name" type="xs:string" use="required" />
                 <xs:attribute name="weight" type="xs:int" use="required" />
               </xs:complexType>
             </xs:element>
           </xs:sequence>
           <xs:attribute name="building" type="xs:string" use="required"/>
         </xs:complexType>
       </xs:element>
     </xs:choice>
     <xs:attribute name="type" />
     <xs:attribute name="name" />
     <xs:attribute name="race" />
     <xs:attribute name="against" />
     <xs:attribute name="probability" />
   </xs:complexType>
  </xs:element>
  <xs:element name="condition">
   <xs:complexType>
     <xs:attribute name="type" type="xs:string" use="required"/>
     <xs:attribute name="population" type="xs:string" use="optional"/>
  </xs:complexType>
</xs:element>

<xs:simpleType name="tech-type">
  <xs:restriction base="xs:string">
    <xs:enumeration value="Stim Packs"/>
    <xs:enumeration value="Lockdown"/>
    <xs:enumeration value="EMP Shockwave"/>
    <xs:enumeration value="Spider Mines"/>
    <xs:enumeration value="Scanner Sweep"/>
    <xs:enumeration value="Tank Siege Mode"/>
    <xs:enumeration value="Defensive Matrix"/>
    <xs:enumeration value="Irradiate"/>
    <xs:enumeration value="Yamato Gun"/>
    <xs:enumeration value="Cloaking Field"/>
    <xs:enumeration value="Personnel Cloaking"/>
    <xs:enumeration value="Burrowing"/>
    <xs:enumeration value="Infestation"/>
    <xs:enumeration value="Spawn Broodling"/>
    <xs:enumeration value="Dark Swarm"/>
    <xs:enumeration value="Plague"/>
    <xs:enumeration value="Consume"/>
    <xs:enumeration value="Ensnare"/>
    <xs:enumeration value="Parasite"/>
    <xs:enumeration value="Psionic Storm"/>
    <xs:enumeration value="Hallucination"/>
    <xs:enumeration value="Recall"/>
    <xs:enumeration value="Stasis Field"/>
    <xs:enumeration value="Archon Warp"/>
    <xs:enumeration value="Restoration"/>
    <xs:enumeration value="Disruption Web"/>
    <xs:enumeration value="Mind Control"/>
    <xs:enumeration value="Dark Archon Meld"/>
    <xs:enumeration value="Feedback"/>
    <xs:enumeration value="Optical Flare"/>
    <xs:enumeration value="Maelstrom "/>
    <xs:enumeration value="Lurker Aspect"/>
    <xs:enumeration value="Healing"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="upgrade-type">
  <xs:restriction base="xs:string">
    <xs:enumeration value="Terran Infantry Armor"/>
    <xs:enumeration value="Terran Vehicle Plating"/>
    <xs:enumeration value="Terran Ship Plating"/>
    <xs:enumeration value="Zerg Carapace"/>
    <xs:enumeration value="Zerg Flyer Carapace"/>
    <xs:enumeration value="Protoss Armor"/>
    <xs:enumeration value="Protoss Plating"/>
    <xs:enumeration value="Terran Infantry Weapons"/>
    <xs:enumeration value="Terran Vehicle Weapons"/>
    <xs:enumeration value="Terran Ship Weapons"/>
    <xs:enumeration value="Zerg Melee Attacks"/>
    <xs:enumeration value="Zerg Missile Attacks"/>
    <xs:enumeration value="Zerg Flyer Attacks"/>
    <xs:enumeration value="Protoss Ground Weapons"/>
    <xs:enumeration value="Protoss Air Weapons"/>
    <xs:enumeration value="Protoss Plasma Shields"/>
    <xs:enumeration value="U-238 Shells"/>
    <xs:enumeration value="Ion Thrusters"/>
    <xs:enumeration value="Titan Reactor"/>
    <xs:enumeration value="Ocular Implants"/>
    <xs:enumeration value="Moebius Reactor"/>
    <xs:enumeration value="Apollo Reactor"/>
    <xs:enumeration value="Colossus Reactor"/>
    <xs:enumeration value="Ventral Sacs"/>
    <xs:enumeration value="Antennae"/>
    <xs:enumeration value="Pneumatized Carapace"/>
    <xs:enumeration value="Metabolic Boost"/>
    <xs:enumeration value="Adrenal Glands"/>
    <xs:enumeration value="Muscular Augments"/>
    <xs:enumeration value="Grooved Spines"/>
    <xs:enumeration value="Gamete Meiosis"/>
    <xs:enumeration value="Metasynaptic Node"/>
    <xs:enumeration value="Singularity Charge"/>
    <xs:enumeration value="Leg Enhancements"/>
    <xs:enumeration value="Scarab Damage"/>
    <xs:enumeration value="Reaver Capacity"/>
    <xs:enumeration value="Gravitic Drive"/>
    <xs:enumeration value="Sensor Array"/>
    <xs:enumeration value="Gravitic Boosters"/>
    <xs:enumeration value="Khaydarin Amulet"/>
    <xs:enumeration value="Apial Sensors"/>
    <xs:enumeration value="Gravitic Thrusters"/>
    <xs:enumeration value="Carrier Capacity"/>
    <xs:enumeration value="Khaydarin Core"/>
    <xs:enumeration value="Argus Jewel"/>
    <xs:enumeration value="Argus Talisman"/>
    <xs:enumeration value="Caduceus Reactor"/>
    <xs:enumeration value="Chitinous Plating"/>
    <xs:enumeration value="Anabolic Synthesis"/>
    <xs:enumeration value="Charon Booster"/>
  </xs:restriction>
</xs:simpleType>

</xs:schema>

=== calebhearth/bwapi/trunk/bwapi/starcraft-folder/bwapi-data/build-order-simple.xml
<?xml version="1.0" encoding="UTF-8"?>

<build-orders xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="build-order.xsd">
  <build-order type="root" name="Crazy mass marine against terran" race="Terran" against="Protoss" probability="100%">
   <train building="Terran Command Center">
     <build name="Terran SCV" weight="1" max-type="auto-effective-gather"/>
   </train>
   <train building="Terran Barracks">
      <build name="Terran Marine" weight="12" />
      <build name="Terran Medic" weight="4" />
      <build name="Terran Firebat" weight="1" />
      <build name="Terran Ghost" weight="1" />
    </train>
    <build name="Terran Barracks" place="barracks" minimal-population="11"/>
    <build name="Terran Barracks" place="barracks" minimal-population="13"/>
    <build name="Terran Command Center" place="natural-expansion" minimal-population="20"/>
    <build name="Terran Engineering Bay" place="engineering-bay" minimal-population="26"/>
    <build name="Terran Refinery" place="refinery" minimal-population="30"/>
    <build name="Terran Academy" place="non-producting-3X2" minimal-population="31"/>
    <build name="Terran Missile Turret" place="turret-entrance-expansion" minimal-population="32"/>
    <build name="Terran Barracks" place="barracks" minimal-population="33"/>
    <invent name="Stim Packs" minimal-population="35" priority="4"/>
    <upgrade name="U-238 Shells" minimal-population="35" priority="4"/>
    <build name="Terran Comsat Station" place="comsat-station" minimal-population="35"/>
    <build name="Terran Comsat Station" place="comsat-station-expansion" minimal-population="35"/>
    <build name="Terran Barracks" place="barracks" minimal-population="37"/>
    <upgrade name="Terran Infantry Armor" level="1" minimal-population="35"/>
    <build name="Terran Factory" place="factory" minimal-population="45"/>
    <build name="Terran Barracks" place="barracks" minimal-population="50"/>
    <build name="Terran Refinery" place="refinery-expansion" minimal-population="51"/>
    <build name="Terran Starport" place="starport" minimal-population="60"/>
    <train building="Terran Starport">
      <build name="Terran Science Vessel" weight="1" />
    </train>
    <upgrade name="Terran Infantry Armor" level="3" minimal-population="35"/>
    <upgrade name="Terran Infantry Weapons" level="3" minimal-population="35"/>
    <build name="Terran Command Center" place="second-expansion"/>
    <build name="Terran Science Facility" place="science-facility"/>
    <build name="Terran Control Tower" place="control-tower"/>
    <build name="Terran Covert Ops" place="covert-ops"/>
    <build name="Terran Barracks" place="barracks"/>
    <build name="Terran Barracks" place="barracks"/>
    <invent name="Lockdown"/>
    <build name="Terran Barracks" place="barracks"/>
    <invent name="EMP Shockwave"/>
    <invent name="Personnel Cloaking"/>
    <build name="Terran Barracks" place="barracks"/>
    <build name="Terran Barracks" place="barracks"/>
    <build name="Terran Nuclear Silo" place="second-expansion-addon"/>
    <train building="Terran Nuclear Silo">
      <build name="Nuclear Missile" weight="1" />
    </train>
  </build-order>
  <build-order type="root" name="Standard terran" race="Terran" against="Zerg" probability="100%">
   <train building="Terran Barracks">
      <build name="Terran Marine" weight="12" />
      <build name="Terran Medic" weight="4" />
      <build name="Terran Firebat" weight="1" />
    </train>
    <build name="Terran Barracks" place="barracks" minimal-population="11"/>
    <build name="Terran Barracks" place="barracks" minimal-population="13"/>
    <build name="Terran Command Center" place="natural-expansion" minimal-population="20"/>
    <build name="Terran Refinery" place="refinery" minimal-population="30"/>
    <build name="Terran Academy" place="non-producting-3X2" minimal-population="31"/>
    <build name="Terran Engineering Bay" place="engineering-bay" minimal-population="26"/>    
    <build name="Terran Barracks" place="barracks" minimal-population="33"/>
    <build name="Terran Refinery" place="refinery-expansion" minimal-population="51"/>
    <invent name="Stim Packs" minimal-population="35" priority="4"/>
    <upgrade name="U-238 Shells" minimal-population="35" priority="4"/>
    <build name="Terran Missile Turret" place="turret-entrance-expansion" minimal-population="32"/>    
    <build name="Terran Comsat Station" place="comsat-station" minimal-population="35"/>
    <build name="Terran Comsat Station" place="comsat-station-expansion" minimal-population="35"/>
    <upgrade name="Terran Infantry Armor" level="1" minimal-population="35"/>
    <build name="Terran Factory" place="factory" minimal-population="45"/>
    <build name="Terran Barracks" place="barracks" minimal-population="50"/>
    <build name="Terran Starport" place="starport"/>
    <train building="Terran Starport">
      <build name="Terran Science Vessel" weight="1" />
    </train>
    <upgrade name="Terran Infantry Armor" level="3"/>
    <upgrade name="Terran Infantry Weapons" level="3"/>
    <build name="Terran Science Facility" place="science-facility"/>    
    <build name="Terran Command Center" place="second-expansion"/>
    <build name="Terran Control Tower" place="control-tower"/>
    <build name="Terran Barracks" place="barracks"/>
    <build name="Terran Barracks" place="barracks"/>
    <build name="Terran Barracks" place="barracks"/>
    <invent name="Irradiate"/>
    <build name="Terran Barracks" place="barracks"/>
    <build name="Terran Barracks" place="barracks"/>
    <build name="Terran Nuclear Silo" place="second-expansion-addon"/>
    <train building="Terran Nuclear Silo">
      <build name="Nuclear Missile" weight="1" />
    </train>
  </build-order>  
</build-orders>
